### ISSUE TITLE
"The page you are looking for cannot be found" message

### ISSUE THREAD

**Issue by Sokuya** [gameplaycolor/gameplaycolor#128]
I haven't play the game in a while, and now when I'm entering the web app I'm getting "The page you are looking for cannot be found".
I want to [extract my saved games](https://www.youtube.com/watch?v=H5MI1CRyL0E&feature=youtu.be) so I can reinstall the web app and continue playing. I read that the [saved game are stored locally on the device](https://gameplaycolor.com/faq/#save).
I didn't update the OS, I didn't erase my phone. How can I found my saved game?
![IMG_2360](https://user-images.githubusercontent.com/60462593/73429186-b498bd00-4343-11ea-84a5-5e4f64235453.PNG)

**Comment by no0bi1** [comment]
Yep was just gonna post this. Before ios13 killed it, it was working fine then the update happened and now the old version is completely gone. What is the point if we can lose data at any point in time?

**Comment by Sokuya** [comment]
I’m using iOS 11. I can start a new save as I install a new web app, but I want my saved game.

**Comment by no0bi1** [comment]
the new web app is fixed for ios13 since database management broke. so ur old web app links to the old site and u get 404. which doesnt make sense, isnt the whole point of Game Play to work offline? you would think the whole thing gets downloaded as an app. 

So I Ask Again, What Is The Point Of This If Data Can Be Lost Anytime?
