### ISSUE TITLE
Mew

### ISSUE THREAD

**Issue by JoseDanger** [gameplaycolor/gameplaycolor#150]
Is there a way you could add mew to the game so we can complete the Pokédex?

**Comment by Xman3684** [comment]
you are still able to do the original Mew Glitch- i literally just did it haha

https://www.wikihow.com/Catch-Mew-in-Pok%C3%A9mon-Yellow

**Comment by jbmorley** [comment]
That glitch is fantastic. Thanks for sharing @Xman3684.

I think I'm going to close this as won't fix @JoseDanger since it's apparently possible to exploit the glitch in Game Play (I've not tried it myself). I'm leaving the issue #51 open which I think it's a more comprehensive approach to your request.
