### ISSUE TITLE
No sound on iPad Pro

### ISSUE THREAD

**Issue by aikewoody** [gameplaycolor/gameplaycolor#227]
First of all I want to thank you all for developing this project and making it open source!

So I just “installed” the Game Play Color by adding the website to my Home Screen. All the .gb and .gbc files I have are running smoothly, only the sound is not working on any of them. The device I’m running it on is: iPad Pro (12.9-inch) (3rd generation) with iPadOS 15.5 (19F77)

Maybe the cause is the game boy files themselves, if you want to check that let me know and I can add a link to them.

**Comment by jbmorley** [comment]
I've double checked this and it seems to be working for me. I've always found the iPad's audio controls to be a little more confusing than on the iPhone as you have to make sure the device isn't in silent mode for the sound to work in-browser, even though that isn't necessary for some other apps. Perhaps that's the issue you were seeing?

Closing as not planned since I don't think there are meaningful changes to make here.
