### ISSUE TITLE
Andriod Support

### ISSUE THREAD

**Issue by JosephLukerTheBest** [gameplaycolor/gameplaycolor#68]
I am suggesting since you are eventually having saves running through drive that you can also make it so  you can play on any device.I know andriod has alternatives but your program has a such unique and amazing feel that it would dominate the google play market.

**Comment by jbmorley** [comment]
Thanks for raising it – makes sense to have it here, even if it's not high up the roadmap :+1:

**Comment by jbmorley** [comment]
Since iPadOS has started pretending the iPad is a Mac, it's getting harder to figure out exactly what device we're running on. It's also pretty antisocial to write a web app and then limit it to a given platform; seems a bit against the spirit of the thing 🙃. Given this, I'm going to see what I can do to add support for other platforms.

So far, I've found it works pretty well on my Pixel 4a with the following issues:

- the 'add to home screen' instructions are obviously wrong
- it's really hard to paste the Google Drive authentication code 
- audio is a bit crunchy (but works 🤯)
- the canvas seems to be using some form of bilinear resizing (instead of nearest neighbour) meaning the screen's pretty fuzzy

**Comment by jbmorley** [comment]
I'm planning to support this as part of the work to support local file uploads and drop Google Drive.
