### ISSUE TITLE
Force Game Boy games with a .gbc extension to be treated as Game Boy Color games

### ISSUE THREAD

**Issue by ghost** [gameplaycolor/gameplaycolor#73]
I patched Pokemon Red to include gen 2 graphics and the Game Play Color is displaying it in normal GB Color palette despite the extension being .gbc. Is this intended behaviour?

**Comment by Shawnjoseph2001** [comment]
I think- I patched a Red ROM and launched it in Game Boy Online and the same thing happened. I could tell that it was patched because of the Gen 2 window borders, but it launched in Game Boy mode. Maybe an update could be made to add an option to force ROMs to run in Game Boy Color mode? Although Game Boy games look terrible booted as Game Boy Color games- run the coin case glitch in Gold or Silver to see for yourself.

**Comment by jbmorley** [comment]
So I guess the goal here is that a .gbc extension forces Game Play Color to treat it as a Game Boy Color game?

**Comment by jbmorley** [comment]
So this is either an issue with the romhack that means it's not correctly identifying as a GBC ROM (which isn't something we can fix here I think). _Or_, it's a manifestation of #239 where we don't support the color modes of SGB enhanced games.

With that in mind, I think I'm going to forward-dupe this to #239 as that describes the feature request pretty well.
